version: '3.1'

services:

  n8n:
    image: n8nio/n8n:${N8N_VERSION}
    restart: always
    environment:
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_PORT=5432
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_PROCESS=main
      - QUEUE_BULL_REDIS_PORT=6379
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=dbuser
      - DB_POSTGRESDB_PASSWORD=dbpassword
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - QUEUE_BULL_REDIS_HOST=${QUEUE_BULL_REDIS_HOST}
      - DB_LOGGING_MAX_EXECUTION_TIME=0
      - N8N_LOG_LEVEL=error
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=none
      - QUEUE_HEALTH_CHECK_ACTIVE=true
    ports:
      - 5679:5678
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - /home/ubuntu/n8n/appdata:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n worker --concurrency=${N8N_CONCURRENCY}"
    